version: '3.7'

services:
  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - comm-net

  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - comm-net

  order-service:
    build:
      context: order_service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    networks:
      - comm-net
    env_file: ./order_service/.env
    depends_on:
      - timescaledb
      - rabbitmq

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    container_name: timescale-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - comm-net

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - comm-net

volumes:
  timescale_data:

networks:
  comm-net:
    name: commerce-network
    driver: bridge